force-app/main/default/objects/Software_License__c/Software_License__c.object-meta.xml
<CustomObject>
    <description>Week 7 Task 8 optional challenge</description>
    <label>Software License</label>
    <nameField>
        <displayFormat>SL-{000}</displayFormat>
        <label>Software License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Software Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_License__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Due to renew</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>To remove</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Week7Task8Controller.cls
public with sharing class Week7Task8Controller {
    @AuraEnabled
    public static void updateCategory(Id softwareId, String category){
        Software_License__c softwareLicense = new Software_License__c();
        softwareLicense.Id = softwareId;
        softwareLicense.Category__c = category;

        update softwareLicense;
    }

    @AuraEnabled
    public static string getCurrentCategory(Id softwareId){
        Software_License__c license = [
            SELECT Category__c
            FROM Software_License__c
            WHERE Id = :softwareId
            LIMIT 1
        ];
        return license.Category__c;
    }
}